### PR TITLE
fix: enhance URL validation for Z.AI image generation

### LINKED ISSUE #5480: [BUG] Z.AI returned an invalid image URL
### Environment

🐧 Linux

### System

Archlinux latest

### Version

1.17.0

### Desktop Information

_No response_

### Describe the problem

Using Z.AI's image generation function will report an error: Z.AI returned an invalid image URL.

The reason is that the code requires that the image URL domain returned by Z.AI must be z.ai, but the official current domain name is ufileos.com, which uses third-party object storage.

### Additional info

_No response_

### Please tick the boxes

- [x] I have explained the issue clearly, and I included all relevant info
- [x] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [x] I have checked the [docs](https://docs.sillytavern.app/) important
- [x] I confirm that my issue is not related to third-party content, unofficial extension or patch. If in doubt, check with a new [user account](https://docs.sillytavern.app/administration/multi-user/) and with extensions disabled

### PR DESCRIPTION
**Pull request by Cohee1207**
Fixes #5480

## Checklist:

- [x] I have read the [Contribution guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

File: src/endpoints/stable-diffusion.js [hunk 1]
```diff
@@ -1906,12 +1906,21 @@ zai.post('/generate', async (request, response) => {
...
         }
 
+        const url = new URL(urlString);
+        if (!url.hostname.endsWith('.z.ai') && !url.hostname.endsWith('.ufileos.com')) {
+            console.warn('Z.AI returned a URL with an unrecognized hostname.');
+            return response.sendStatus(500);
+        }
+
+        // Sometimes the URL is valid but the image isn't immediately available
+        await delay(2000);
```
Comment (Wolfsblvt) [inline src/endpoints/stable-diffusion.js]: Are we always waiting 2 seconds, even when it's available right away? Is that convenient?

**Review by Wolfsblvt — APPROVED** [review]

File: src/endpoints/stable-diffusion.js (hunk 1 above)
Comment (Cohee1207) [reply src/endpoints/stable-diffusion.js]: I could add a plain retry on 404 code if that'll make it more robust

Comment (Wolfsblvt) [reply src/endpoints/stable-diffusion.js]: Possibly. I dunno, I don't have any horses in this, so I don't mind too much.
But if image gen was done fast (a few seconds) and you add two seconds on top, *just to be safe*, eh. I mean, users likely wouldn't notice it.

Comment (Cohee1207) [reply src/endpoints/stable-diffusion.js]: https://github.com/SillyTavern/SillyTavern/pull/5482/commits/df783ac3907feff835151f0bf07eb85b1e7322e4
