### PR TITLE
Better IPv6 support

### LINKED ISSUE #3416: [BUG] DNS error 3008 'ENOTFOUND' while looking up `[::]` leads to a failure on enabling IPv6 in docker
### Environment

🐋 Docker

### System

Unraid 7.0.0 (Kernel: 6.6.68), Docker version 27.0.3 (build 7d4bcd8)

### Version

From 1.12.10 to Staging

### Desktop Information

Official `https://github.com/sillytavern/SillyTavern/pkgs/container/sillytavern` docker image.

### Describe the problem

I am deploying SillyTavern on my Unraid 7.0.0 (Kernel: 6.6.68) with Docker version 27.0.3 (build 7d4bcd8) with the following command given on GitHub page:
```
docker create --name='sillytavern' --net='[DockerNet]' -p '8000:8000/tcp' -v '[plugins]':'/home/node/app/plugins':'rw' -v '[config]':'/home/node/app/config':'rw' -v '[data]':'/home/node/app/data':'rw' -v '[extensions]':'/home/node/app/public/scripts/extensions/third-party':'rw' 'ghcr.io/sillytavern/sillytavern:[version]'
```
I can make sure that my Unraid and docker could have ipv6 address normally and with the custom `config.yaml` to only enable ipv6:
```
listen: true
protocol:
  ipv4: false
  ipv6: true
dnsPreferIPv6: true
```
The container would terminate itself as soon as it starts. It shows the following error in the log, no matter whether I use `bridge`/`host`/`br0` network type.
```
Node version: v22.12.0. Running in production environment. Server directory: /home/node/app
Preferring IPv6 for DNS resolution
Using data root: ./data
SillyTavern 1.12.10
Compiling frontend libraries...
webpack 5.95.0 compiled successfully in 5477 ms
non-fatal error: failed to start server on IPv6
Error: getaddrinfo ENOTFOUND [::]
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '[::]'
}
fatal error: Failed to start server on IPv6 and IPv4 disabled
```
I have tested all version after the commit `da5581e` with the pull #2593 and they all have the same problem.

### Additional info

_No response_

### Please tick the boxes

- [x] I have explained the issue clearly, and I included all relevant info
- [x] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [x] I have checked the [docs](https://docs.sillytavern.app/) important

### PR DESCRIPTION
**Pull request by Cohee1207**
Fixes #3416

The code is courtesy of @BPplays

## Checklist:

- [X] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

File: server.js [hunk 1]
```diff
@@ -1065,9 +1064,6 @@ async function startServer() {
                 process.exit(1);
             }
         }
-
-    } else {
-        console.log('Neither protocol: ipv6, nor ipv4 are set to auto, skipping detection');
```
Comment (BPplays) [inline server.js]: @Cohee1207 im not sure i 100% agree with this, that log is to tell the user: detection messages for if the user has ipv6 and/or ipv4 won't show up. and to not use that to judge a potential network problem

Comment (Cohee1207) [reply server.js]: We generally shouldn't log things that are not happening. This log just creates an unwanted noise for existing users who don't care about auto detection and/or had chosen their protocol deliberately.
