### PR TITLE
Fix `{{firstIncludedMessageId}}` to not rely on DOM

### LINKED ISSUE #3281: [BUG] `{{firstIncludedMessageId}}` bug with limited message load
### Environment

🪟 Windows

### System

FireFox

### Version

1.12.10 staging

### Desktop Information

_No response_

### Describe the problem

I think I found a bug with `{{firstIncludedMessageId}}`. 
It seems like if the chat history isn't loaded enough (due to limited 'Msg.to load'), it uses the first visible message ID (msg last InContext llin) instead of the actual first message ID. 
Can this be fixed without increasing the msg load count?

### Additional info

_No response_

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) important

### PR DESCRIPTION
**Pull request by Wolfsblvt**
Up until now, the `{{firstIncludedMessageId}}` macro relied on searching the DOM for the actual CSS class applied for the context line. Bad design, as the actual message was maybe not display, with display X messages enabled.

Fixes #3281

#### Changes
- Use `setInContextMessages()` that sets the context line on generation to also update a chat metadata field
- Utilize that field inside the macro
- Update docs to clarify that this will only show the mesid that was relevant during last generation

## Checklist:

- [x] I have read the [Contributing guidelines](https://www.youtube.com/watch?v=vDWlhQjGjoc).

### CODE REVIEW

**Comment by Wolfsblvt** [comment]
This should be tested on Text Completion.
While testing this, I also realized that that the context number for Chat Completion is broken, as it includes more messages than there are in chat, so it'll use the wrong number, even with a context limit.
I don't know how to fix that though, and that's a separate issue.

image

File: public/script.js [hunk 1]
```diff
@@ -5429,20 +5429,24 @@ async function promptItemize(itemizedPrompts, requestedMesId) {
...
     lastMessageBlock.addClass('lastInContext');
 
     if (lastMessageBlock.length === 0) {
         const firstMessageId = getFirstDisplayedMessageId();
         $(`#chat .mes[mesid="${firstMessageId}"`).addClass('lastInContext');
     }
+
+    const lastMessageId = Math.max(0, chat.length - msgInContextCount);
+    chat_metadata['lastInContextMessageId'] = lastMessageId;
+    saveMetadataDebounced();
```
Comment (Cohee1207) [inline public/script.js]: Eh, I'd rather not to prevent unnecessary saves.
Even if the metadata field is lost, it's not that bad.

Comment (Wolfsblvt) [reply public/script.js]: If it's not saved, then worst case there is no id at all until the next generation, yeah.

**Review by Cohee1207 — APPROVED** [review]
