### PR TITLE
Fix "show more messages" on empty chat

### LINKED ISSUE #2586: [BUG] Show more messages
### Environment

🪟 Windows

### System

brave

### Version

0c2df51e

### Desktop Information

Windows  / Android

### Describe the problem

In a chat window with a character, if user delete message up to show more messages, when clicking on Show more messages nothing happen.  No Error in the console.  Msg. to load set to 5.

### Additional info

_No response_

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) important

### PR DESCRIPTION
**Pull request by Wolfsblvt**
- Fixes lazy loading of chat when all messages were deleted
- Fixes #2586

## Checklist:

- [x] I have read the [Contributing guidelines](https://www.youtube.com/watch?v=dQw4w9WgXcQ).

### CODE REVIEW

File: public/script.js [hunk 1]
```diff
@@ -1720,16 +1720,24 @@ export async function replaceCurrentChat() {
...
 
 export function showMoreMessages() {
-    let messageId = Number($('#chat').children('.mes').first().attr('mesid'));
+    const firstDisplayedMesId = $('#chat').children('.mes').first().attr('mesid');
+    let messageId = Number(firstDisplayedMesId);
     let count = power_user.chat_truncation || Number.MAX_SAFE_INTEGER;
 
+    // If there are no messages displayed, or the message somehow has no mesid, we default to one higher than last message id,
+    // so the first "new" message being shown will be the last available message
+    if (!messageId) {
```
Comment (Cohee1207) [inline public/script.js]: Shouldn't it be `if (isNaN(messageId))`?

Comment (Wolfsblvt) [reply public/script.js]: Possibly. I mean, it's nearly the same. And in that case it doesn't matter that it can be 0, because in that case we cannot prepend anyway, so both work...
image

But being more direct in intention never hurts.

(see, that what it leads to when you do JS devving. Over-reliance on *eh, the language says this is falsey anyway, so just go with it xD )

**Review by Cohee1207 — APPROVED** [review]
