### PR TITLE
Fix copy actions for non-HTTPS/localhost

### LINKED ISSUE #2352: [BUG] Missing "Copy" button in the Message Actions, bar when using mobile phone tunnel.
### Environment

🪟 Windows

### System

Samsung and Chrome browsers

### Version

SillyTavern 1.12.0 'release' (56392c17)

### Desktop Information

SillyTavern: 1.12.0 'release' (56392c17)
Node: v18.18.2
OpenAI-compatible API
Kunoichi-7B-GPTQ

### Describe the problem

On android cellphone using Local direct IP or using NordVPN MeshNet to share local addresses over internet. The "Copy" button on the Message Actions bar, is missing. I don't know why it's the only button that seems to be missing (that I've noticed).

When using Ngrok tunneling service, the "Copy" button did appear with the same phone browsers, both Samsung and Chrome browsers. On the host PC, the "Copy" button is there as well. I don't need it on the PC and I stop using Ngrok.
It is important on the phone for ease of use. I don't know how to force it to be there all the time.

"Expand Message Actions" is checked. Not using CSS or ad blockers.

### Additional info

[https://www.reddit.com/r/SillyTavernAI/comments/1d3s5yq/missing_copy_button_in_the_message_actions_bar/](url)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) important

### PR DESCRIPTION
**Pull request by Cohee1207**
Fixes #2352

## Checklist:

- [X] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

File: public/script.js [hunk 1]
```diff
@@ -5469,15 +5469,15 @@ async function promptItemize(itemizedPrompts, requestedMesId) {
     } else {
         diffPrevPrompt.style.display = 'none';
     }
-    popup.dlg.querySelector('#copyPromptToClipboard').addEventListener('click', function () {
+    popup.dlg.querySelector('#copyPromptToClipboard').addEventListener('pointerup', async function () {
```
Comment (Wolfsblvt) [inline public/script.js:5472]: Why? Did you see the need to capture right click and middle mouse as well for the copy? that's a bit weird.
Or like, you could click somewhere, drag and end up on the copy button and it copies?

Not how I'd expect a copy button to work.

File: public/script.js [hunk 2]
```diff
@@ -10572,24 +10572,18 @@ jQuery(async function () {
...
-            if (this_chid !== undefined || selected_group || name2 === neutralCharacterName) {
-                try {
-                    const messageId = $(this).closest('.mes').attr('mesid');
-                    const text = chat[messageId]['mes'];
-                    navigator.clipboard.writeText(text);
-                    toastr.info('Copied!', '', { timeOut: 2000 });
-                } catch (err) {
-                    console.error('Failed to copy: ', err);
-                }
+    $(document).on('pointerup', '.mes_copy', async function () {
```
Comment (Wolfsblvt) [inline public/script.js:10575]: Okay, whoops, now I see why. You just changed it to be consistent. But I still think it should be `click` and not `pointerup`.

File: public/scripts/utils.js [hunk 3]
```diff
@@ -391,6 +391,26 @@ export function getStringHash(str, seed = 0) {
...
+ * @param {string} text - The text to copy to the clipboard.
+ * @returns {Promise<void>} A promise that resolves when the text has been copied to the clipboard.
+ */
+export function copyText(text) {
+    if (navigator.clipboard) {
+        return navigator.clipboard.writeText(text);
+    }
+
+    const parent = document.querySelector('dialog[open]:last-of-type') ?? document.body;
+    const textArea = document.createElement('textarea');
```
Comment (Wolfsblvt) [inline public/scripts/utils.js:405]: Sneaky, clever.
Doesn't this lead to a possible visible draw/redraw of the UI with the textarea appearing?
Maybe make adding a CSS class to make it absolute and out of screen would make 100% sure.

**Review by Wolfsblvt — APPROVED** [review]
Well, I can't really test that, as I have no idea how I could simulate the copying **not** working. And I don't wanna set up remote access, because I am lazy.

Besides the two small points I mentioned, code looks good though.
The normal functionality still works, and copying on a  text field like this works too, so yeah. Good idea.

File: public/script.js (hunk 1 above)
Comment (Cohee1207) [reply public/script.js:5472]: I think it's originally a Safari workaround.

> The implementation is available through the navigator.clipboard API which must be called within user gesture event handlers like pointerdown or **pointerup**...

File: public/scripts/utils.js (hunk 3 above)
Comment (Cohee1207) [reply public/scripts/utils.js:405]: Nope, the textarea is removed from DOM before it could be painted.

Comment (Wolfsblvt) [reply public/scripts/utils.js:405]: Okay, good then.

File: public/script.js (hunk 1 above)
Comment (Wolfsblvt) [reply public/script.js:5472]: Blergh. Weird browser workarounds again.
It's just weird on any "normal" browser now, because yeah. Right click is the most glaring one. Dunno if there is a way around it.
Could maybe check for the mouse button pressed int the event handler. That wouldn't remove the weird thing if you click, drag and release on the button, but at least disable all other buttons than left click.

Comment (Cohee1207) [reply public/script.js:5472]: I don't think that right mouse click will do anything destructive unless you are preventing the default context menu.
