### PR TITLE
Fix corruption due to this_chid shift

### LINKED ISSUE #3667: [BUG] Character data corrupted with another character
### Environment

🪟 Windows

### System

Windows 11 pro | 10.0.22621 Build 22621 

### Version

1.12.12 | staging | 137927bb4 

### Desktop Information

- nodejs version : v23.9.0 
- browser : thorium SSE3 , ver 130.0.6723.174 

### Describe the problem

[NSFW waring]
when I just chatting with a character https://chub.ai/characters/Anonymous/liliana-lily-vance-female-best-friend-is-too-clingy-c37ce99a1534 suddenly I got changed to the character https://files.catbox.moe/y754o0.png after a 2 - 3 chat and got switched I notice that the greeting is still there and when I check the character tab the definition is from the second character *I didn't check the greeting yet* and when I come to the first character is lost the all of the chat of the first character go to second character 
here is a chat files https://files.catbox.moe/og46vo.jsonl 
I didn't use the group chat for it so, sorry for my weird explanation then ._.

### Additional info

_No response_

### Please tick the boxes

- [x] I have explained the issue clearly, and I included all relevant info
- [x] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [x] I have checked the [docs](https://docs.sillytavern.app/) important
- [x] I confirm that my issue is not related to third-party content, unofficial extension or patch. If in doubt, check with a new [user account](https://docs.sillytavern.app/administration/multi-user/) and with extensions disabled

### PR DESCRIPTION
**Pull request by Cohee1207**
Okay, we're trying to tame ancient beasts again, this time `getCharacters`. **Possibly** fixes #3667. We're not trying to fix all cases with data desync, but at least prevent obvious loss.

There are two cases worth noting, both relate to external data manipulations. Both may potentially lead to corruptions due to this_chid shifting on the next getCharacters() call.

1. Character gets deleted on backend but still exist on frontend.
2. Character is dropped-in to /characters folder

It's recommended to test on a clean account for easier setup to test the fix.

1. Create two characters named "Bob" and "Alice". Open a chat with "Bob", then delete his card from a folder and trigger any action that refreshes a list, i.e. creating a new character or pressing "Convert to group" from the burger menu. You should see a popup that Bob is gone. It's better to bail out now and refresh.
2. Create a character named "Bob". Then drop a file into a characters folder that will shift his thid_chid upwards, i.e. "Alice". Trigger any action that causes a refresh (see above). Reload the chat with Bob and type something in his description fields. Refresh the page. Verify that Bob's data stays with Bob and doesn't corrupt Alice.

## Checklist:

- [X] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

File: public/script.js [hunk 1]
```diff
@@ -1799,8 +1800,17 @@ export async function getCharacters() {
...
             characters[i]['chat'] = String(characters[i]['chat']);
         }
-        if (this_chid !== undefined) {
-            $('#avatar_url_pole').val(characters[this_chid].avatar);
+
+        if (previousAvatar) {
+            const newCharacterId = characters.findIndex(x => x.avatar === previousAvatar);
+            if (newCharacterId >= 0) {
+                setCharacterId(newCharacterId);
+                await unshallowCharacter(String(newCharacterId));
```
Comment (Wolfsblvt) [inline public/script.js]: There are other things that depend on chid. Found those on first glance:
https://github.com/SillyTavern/SillyTavern/blob/79a8080b7d11f5d905590f659f268b5de6c79051/public/script.js#L7851-L7854

You should likely just call `selectCharacterById`, which should handle all that. If you set the chid before, it runs into the second branch that is designed to "select the already selected character".
Yes, it will load the char into the char panel, if you just had the list open. That is unfortunate. But a trade-off I'd say is okay, so we do not have to rewrite every single piece where chid might be relevant.

**Review by Wolfsblvt — CHANGES_REQUESTED** [review]

**Review by Wolfsblvt — APPROVED** [review]
Tested your two scenarios, and tried to play around with a few more.
Works as described.

Weird scenario to happen, but I figure there are enough people actually downloading and manually dropping cards into the folder.

> [!IMPORTANT]  
> Remember to squash the commits please.
