### PR TITLE
Remove unnecessary check for swipe info to fix #4717

### LINKED ISSUE #4717: [BUG] Valid swipe structure in chat files ignored when swipe_info not present.
### Environment

🪟 Windows

### System

Firefox

### Version

1.13.5+

### Desktop Information

Windows, but it doesn't matter this is universal.

### Describe the problem

When a message in chat files does not include "swipes_info", swipes will not be rendered, instead it will only show the first swipe message for all swipes. It does show the correct number of swipes, but it will not update the message text appropriately. 

The information in "swipes_info" is not necessary to display all swipes, so only the actual "swipes" array should be considered mandatory, instead of early returning incorrectly when swipes are present but have no generation info associated with them, which results in incorrect UI behaviour of showing every single swipe as having the same message text, which does not accurately reflect the data in the chat file. The issue is from behaviour in `syncSwipeToMes()` within `script.js`.
Here's the commit and relevant line:
https://github.com/SillyTavern/SillyTavern/commit/ca53323a084a4269572f9d5a94f36d163adac843#diff-4a4ec86e4c05b413e9b128d0f702c797e4a2afd8be513301c019824560d0c8e6R6349

### Additional info

_No response_

### Please tick the boxes

- [x] I have explained the issue clearly, and I included all relevant info
- [x] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [x] I have checked the [docs](https://docs.sillytavern.app/) important
- [x] I confirm that my issue is not related to third-party content, unofficial extension or patch. If in doubt, check with a new [user account](https://docs.sillytavern.app/administration/multi-user/) and with extensions disabled

### PR DESCRIPTION
**Pull request by docfail**
Fix for #4717

## Details on the issue itself
When a chat jsonl has swipes, but no swipe_info associated with a message, the UI incorrectly displays the correct *number* of swipes, but does not correctly display the swipes when swiping, instead it will indicate that you have swiped, but it will display the same message, never updating it, which makes it appear as though all swipes have the same text, despite that not being what is in the chat file.

The swipe_info is _not actually needed_ to display the swipes, so there is no need to strictly check for it and cause incorrect frontend behaviour if it is not present. It's better to only check for the swipes themselves, which **are** actually needed.

## To test
Use a chat file with swipes, but no swipe_info object included on the message. Verify that the messages display correctly when swiping in the UI. If the behaviour appears normal, the fix is working.

## Checklist:

- [x] I have read the [Contribution guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

**Comment by DeclineThyself** [comment]
Context from @Wolfsblvt:

https://github.com/SillyTavern/SillyTavern/pull/4610#issuecomment-3379188067
>Ah I see. syncSwipeToMes and syncMesToSwipe are both intended to only work and do their stuff if the messages are correctly set up for "swipes", meaning they have the info object, etc. So we don't add swipe data before cloning in other functions, or to messages which shouldn't have swipes.

**Comment by docfail** [comment]
> Context from @Wolfsblvt:
> 
> [#4610 (comment)](https://github.com/SillyTavern/SillyTavern/pull/4610#issuecomment-3379188067)
> 
> > Ah I see. syncSwipeToMes and syncMesToSwipe are both intended to only work and do their stuff if the messages are correctly set up for "swipes", meaning they have the info object, etc. So we don't add swipe data before cloning in other functions, or to messages which shouldn't have swipes.

I'm sure there was a fine rationale for the check, I don't begrudge them for making it overly strict. 

However, as I **just** finished the BYAF import update and there's no meaningful way to populate that info (_I could get the "send date" potentially, or maybe it would be the "gen finished date" in this case(?), but literally everything else could not be populated_), I need to strip the check back to only error out when *strictly* necessary. Furthermore, the behaviour that is displayed when swipes are present but no swipe info is present could never be construed to be "correct" even by the most lenient of users, but I don't think they'd have considered testing that to see what that looks like.

**Comment by DeclineThyself** [comment]
> However, as I **just** finished the BYAF import update and there's no meaningful way to populate that info (_I could get the "send date" potentially, or maybe it would be the "gen finished date" in this case(?), but literally everything else could not be populated_), I need to strip the check back to only error out when _strictly_ necessary. Furthermore, the behavior that is displayed when swipes are present but no swipe info is present could never be construed to be "correct" even by the most lenient of users, but I don't think they'd have considered testing that to see what that looks like.

I agree with the change, but it's not my function. That's why I mentioned @Wolfsblvt .

File: public/script.js [hunk 1]
```diff
@@ -6069,7 +6069,7 @@ export function syncSwipeToMes(messageId = null, swipeId = null) {
         return false;
     }
 
-    const targetSwipeInfo = targetMessage?.swipe_info[targetSwipeId];
+    const targetSwipeInfo = targetMessage?.swipe_info?.[targetSwipeId];
```
Comment (Cohee1207) [inline public/script.js:6082]: I propose backfilling the `swipe_info` array if it doesn't exist with some placeholder values:

* `send_date` - send_date from targetMessage
* `gen_started` - undefined
* `gen_finished` - undefined
* `extra` - empty object `{}`

The number of entries will correspond to swipes array length.

Comment (Cohee1207) [reply public/script.js:6082]: That's how first messages are filling it:

https://github.com/SillyTavern/SillyTavern/blob/e9cd32a123f49c1f5d2f42f4320021007c1e9a50/public/script.js#L6723-L6728

Comment (docfail) [reply public/script.js:6082]: Will code that's reliant upon that data be fine with it being mostly undefined?
EDIT: I keep missing your second messages. Really wish github updated or at least let me know before I hit send that a new reply came in 😅

**Comment by Cohee1207** [comment]
I think it's fine for us to auto-fix or backfill it. Historically, ST is very lenient towards incomplete data and should be flexible enough to support incompleteness of incoming data.

File: public/script.js (hunk 1 above)
Comment (docfail) [reply public/script.js:6082]: Update: This is done. I backfilled it with exactly that. Strange though, it looks like targetMessage.send_date is undefined so the swipe_info object ends up just being `{"extra":{}}`. It works but should I pull the date from somewhere else or leave it as-is?

Comment (Cohee1207) [reply public/script.js:6082]: It's fine if send date is missing, it'll just display an empty timestamp in chat.

Comment (docfail) [reply public/script.js:6082]: Alright, then I think this is resolved, let me know if there's anything else.

Comment (Cohee1207) [reply public/script.js:6082]: Nah, it's good. Let me do a quick test and we can merge.

**Review by Cohee1207 — APPROVED** [review]
