### PR TITLE
 Fixes #4950:try to modify config.yaml at start instead of modify it

### LINKED ISSUE #4950: [BUG] fails to start when config is read-only
### Environment

🐋 Docker

### System

NixOS 25.11, Docker 28.5.1

### Version

1.15.0

### Desktop Information

_No response_

### Describe the problem

when the config file is mounted as read-only, the app fails to start:

```sh
$ docker run ... '--mount=type=bind,source=.../config.yaml,target=/home/node/app/config/config.yaml,ro' ...
```

```
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]: Using config path: ./config.yaml
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]: Adding missing config values to config.yaml: [
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'dataRoot',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'listen',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'listenAddress.ipv4',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'listenAddress.ipv6',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'protocol.ipv4',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'protocol.ipv6',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'dnsPreferIPv6',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'browserLaunch.enabled',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'browserLaunch.browser',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'browserLaunch.hostname',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'browserLaunch.port',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'browserLaunch.avoidLocalhost',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'port',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'ssl.enabled',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'ssl.certPath',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'ssl.keyPath',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'ssl.keyPassphrase',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'whitelistMode',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'enableForwardedWhitelist',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'whitelist',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'whitelistDockerHosts',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'basicAuthMode',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'basicAuthUser.username',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'basicAuthUser.password',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'enableCorsProxy',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'requestProxy.enabled',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'requestProxy.url',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'requestProxy.bypass',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'perUserBasicAuth',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'sso.autheliaAuth',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'sso.authentikAuth',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'hostWhitelist.enabled',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'hostWhitelist.scan',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'hostWhitelist.hosts',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'sessionTimeout',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'disableCsrfProtection',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'securityOverride',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'logging.enableAccessLog',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'logging.minLogLevel',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'rateLimiting.preferRealIpHeader',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'backups.common.numberOfBackups',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'backups.chat.enabled',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'backups.chat.checkIntegrity',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'backups.chat.maxTotalBackups',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'backups.chat.throttleInterval',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'thumbnails.enabled',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'thumbnails.format',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'thumbnails.quality',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'thumbnails.dimensions.bg',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'thumbnails.dimensions.avatar',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'thumbnails.dimensions.persona',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'performance.lazyLoadCharacters',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'performance.memoryCacheCapacity',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'performance.useDiskCache',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'cacheBuster.enabled',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'cacheBuster.userAgentPattern',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'allowKeysExposure',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'skipContentCheck',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'whitelistImportDomains',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'requestOverrides',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'extensions.enabled',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'extensions.autoUpdate',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'extensions.models.autoDownload',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'extensions.models.classification',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'extensions.models.captioning',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'extensions.models.embedding',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'extensions.models.speechToText',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'extensions.models.textToSpeech',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'enableDownloadableTokenizers',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'promptPlaceholder',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'openai.randomizeUserId',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'openai.captionSystemPrompt',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'deepl.formality',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'mistral.enablePrefix',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'ollama.keepAlive',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'ollama.batchSize',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'claude.enableSystemPromptCache',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'claude.cachingAtDepth',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'claude.extendedTTL',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'gemini.apiVersion',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'gemini.enableSystemPromptCache',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'gemini.image.personGeneration',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'enableServerPlugins',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   'enableServerPluginsAutoUpdate'
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]: ]
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]: FATAL: Could not add missing config values to config.yaml Error: EROFS: read-only file system, open './config.yaml'
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:     at Object.writeFileSync (node:fs:2415:20)
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:     at addMissingConfigValues (file:///home/node/app/src/config-init.js:239:12)
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:     at initConfig (file:///home/node/app/src/config-init.js:252:5)
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:     at CommandLineParser.parse (file:///home/node/app/src/command-line.js:272:9)
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:     at file:///home/node/app/server.js:8:41
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:     at ModuleJob.run (node:internal/modules/esm/module_job:413:25)
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:     at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:     at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:660:26)
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:     at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5) {
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   errno: -30,
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   code: 'EROFS',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   syscall: 'open',
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]:   path: './config.yaml'
Jan 04 16:30:55 kennel docker-sillytavern-start[3593497]: }
```

### Additional info

_No response_

### Please tick the boxes

- [x] I have explained the issue clearly, and I included all relevant info
- [x] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [x] I have checked the [docs](https://docs.sillytavern.app/) important
- [x] I confirm that my issue is not related to third-party content, unofficial extension or patch. If in doubt, check with a new [user account](https://docs.sillytavern.app/administration/multi-user/) and with extensions disabled

### PR DESCRIPTION
**Pull request by san-tian**
## Checklist:

- [x ] I have read the [Contribution guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

File: src/config-init.js [hunk 1]
```diff
@@ -236,7 +236,11 @@ export function addMissingConfigValues(configPath) {
             console.log('Migrating config values in config.yaml:', migratedKeys);
         }
 
-        fs.writeFileSync(configPath, yaml.stringify(config));
+        try {
```
Comment (Cohee1207) [inline src/config-init.js]: Isn't it getting caught by the outer catch? While it says FATAL, it's not actually fatal in a way it prevents a startup.

Comment (san-tian) [reply src/config-init.js]: You’re right. There is already an outer catch, so we shouldn’t stack another catch here. I suggest changing the outer `console.error` to `console.warn`, since it doesn’t actually affect startup. (Personally, I think this is a minor issue, but since someone raised it in  #4950 , it makes sense to address it.)

Also, I apologize for the careless change. This is my first PR, and I’m still getting familiar with the process.

Comment (Cohee1207) [reply src/config-init.js]: Well, that might make a bit more sense:

`console.error` => `console.warn`
`.red` => `.yellow`
`FATAL:` in the message => remove

It's usually a sign of something being wrong with your setup anyway, so the warning is not unwarranted.

Comment (san-tian) [reply src/config-init.js]: Thanks. I have made the modifications and commited.

**Review by Cohee1207 — APPROVED** [review]
