### PR TITLE
Fix renaming characters losing connections of several aux fields

### LINKED ISSUE #3488: [BUG] Optional character lorebooks don't get saved when changing character name
### Environment

🪟 Windows

### System

Windows

### Version

Newest branching

### Desktop Information

_No response_

### Describe the problem

When a character's name is changed, only the primary lorebook is saved with the new name. All the additional lorebooks (optional lorebooks) get disattached upon name change. Please make it so the optional lorebooks are kept when the character's name is changed.

### Additional info

_No response_

### Please tick the boxes

- [x] I have explained the issue clearly, and I included all relevant info
- [x] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [x] I have checked the [docs](https://docs.sillytavern.app/) important
- [x] I confirm that my issue is not related to third-party content, unofficial extension or patch. If in doubt, check with a new [user account](https://docs.sillytavern.app/administration/multi-user/) and with extensions disabled

### PR DESCRIPTION
**Pull request by Wolfsblvt**
Update renaming characters to respect and move several of the auxiliary data connections to the new name, not *forgetting* them.

### Changes
- Move WI char lore (additional lorebooks) based on rename
- Move character-bound Author's Note based on rename
- Extend core `getCharFilename` to be able to take an avatarKey, instead of just uid 
- Update "active character" field on char rename
- Auto-load char/group resets if target is not found
- Add event `event_types.CHARACTER_RENAMED` for extensions to listen to on renamed character, to modify/move stuff if they need to.

Fixes #3488.

## Checklist:

- [x] I have read the [Contributing guidelines](https://www.youtube.com/watch?v=B5nim_i_PiM).

## Copilot
This pull request includes several changes to the `public/script.js` and related files to enhance functionality and improve code clarity. The most important changes include adding new event types, updating functions to handle active characters and groups more robustly, and improving the handling of character renaming.

Enhancements to event handling and functions:

* [`public/script.js`](diffhunk://#diff-4a4ec86e4c05b413e9b128d0f702c797e4a2afd8be513301c019824560d0c8e6R496): Added a new event type `CHARACTER_RENAMED` to the `event_types` object.
* [`public/script.js`](diffhunk://#diff-4a4ec86e4c05b413e9b128d0f702c797e4a2afd8be513301c019824560d0c8e6R1031-R1046): Updated `setActiveCharacter` and `setActiveGroup` functions to reset the active entity if none is provided, and to ensure only one entity (character or group) is active at a time.

Improvements to character renaming:

* [`public/script.js`](diffhunk://#diff-4a4ec86e4c05b413e9b128d0f702c797e4a2afd8be513301c019824560d0c8e6L6244-R6283): Enhanced the `renameCharacter` function to update additional fields and emit the `CHARACTER_RENAMED` event when a character is renamed.

Error handling and logging improvements:

* [`public/scripts/RossAscends-mods.js`](diffhunk://#diff-945d6d3576a92ebc6111470aa7b7e6fa33c13ce5c4f0e3af1a5a0157550150c5R290-R304): Added error handling and logging to reset the active character or group if they are not found or if both are set simultaneously.

Function return value adjustments:

* [`public/scripts/group-chats.js`](diffhunk://#diff-87068eb81cbdcdeccc61b128947e5a25793616860a506c3c89338585c774f92dL1667-R1672): Modified `openGroupById` to return a boolean indicating success or failure. [[1]](diffhunk://#diff-87068eb81cbdcdeccc61b128947e5a25793616860a506c3c89338585c774f92dL1667-R1672) [[2]](diffhunk://#diff-87068eb81cbdcdeccc61b128947e5a25793616860a506c3c89338585c774f92dR1689-R1693)

These changes collectively improve the robustness and clarity of the codebase, particularly in handling character and group states.

### CODE REVIEW

File: public/script.js [hunk 1]
```diff
@@ -6241,9 +6252,35 @@ export async function renameCharacter(name = null, { silent = false, renameChats
...
+                saveSettingsDebounced();
+            }
+
+            // Update active character, if the current one was the currently active one
+            if (active_character === oldAvatar) {
+                active_character = newAvatar;
+                saveSettingsDebounced();
+            }
+
+            eventSource.emit(event_types.CHARACTER_RENAMED, oldAvatar, newAvatar);
```
Comment (Cohee1207) [inline public/script.js]: Event emission should be awaited to let extensions run before refreshing

File: public/script.js [hunk 2]
```diff
@@ -7570,7 +7607,7 @@ export function select_selected_character(chid) {
     // Hide the chat scenario button if we're peeking the group member defs
     $('#set_chat_scenario').toggle(!selected_group);
 
-    // Don't update the navbar name if we're peeking the group member defs
+    // Don't update the navbar name if we're peekinFg the group member defs
```
Comment (Cohee1207) [inline public/script.js]: Wut happened here?

File: public/scripts/RossAscends-mods.js [hunk 3]
```diff
@@ -287,10 +287,21 @@ async function RA_autoloadchat() {
...
         }
 
         if (active_group !== null && active_group !== undefined) {
-            await openGroupById(String(active_group));
+            if (active_character) {
+                console.warn('Active character and active group are both set. Only active character will be loaded. Resetting active group.');
+                setActiveGroup(null);
+                saveSettingsDebounced();
+            } else {
+                const result = await openGroupById(String(active_group));
```
Comment (Cohee1207) [inline public/scripts/RossAscends-mods.js:302]: Unused result should be discarded

**Review by Cohee1207 — CHANGES_REQUESTED** [review]

File: public/scripts/RossAscends-mods.js (hunk 3 above)
Comment (Wolfsblvt) [reply public/scripts/RossAscends-mods.js:302]: It's not unused. If there is no valid group to be found, it resets the `active_group` value. If there is one, it successfully opens/selects it.

File: public/script.js (hunk 2 above)
Comment (Wolfsblvt) [reply public/script.js]: Angrily typing characters on my keyboard without thinking. Move along...

File: public/scripts/RossAscends-mods.js (hunk 3 above)
Comment (Cohee1207) [reply public/scripts/RossAscends-mods.js:302]: I mean that the function result is saved to a variable that is declared in a scope and then not used after.

File: public/script.js (hunk 1 above)
Comment (Wolfsblvt) [reply public/script.js]: Makes sense. Done.

File: public/scripts/RossAscends-mods.js (hunk 3 above)
Comment (Wolfsblvt) [reply public/scripts/RossAscends-mods.js:302]: I still don't understand what you mean. The result is used inside the `if (!result)` block below to reset the active group id if not found.

What exactly do you mean?

Comment (Cohee1207) [reply public/scripts/RossAscends-mods.js:302]: > The result is used inside the if (!result) block below to reset the active group id if not found.

Where? I don't see it.

image

Comment (Wolfsblvt) [reply public/scripts/RossAscends-mods.js:302]: I don't even know how to respond to this. I had this all done, and the file was still locally staged, not committed.
Don't ask me.
Pretend this never happened?

File: public/scripts/RossAscends-mods.js [hunk 4]
```diff
@@ -287,10 +287,26 @@ async function RA_autoloadchat() {
                 const selectedCharElement = $(`#rm_print_characters_block .character_select[chid="${active_character_id}"]`);
                 applyTagsOnCharacterSelect.call(selectedCharElement);
             }
+            if (!active_character_id) {
```
Comment (Cohee1207) [inline public/scripts/RossAscends-mods.js]: What are the type of active_character_id and active_character? Can they ever be numbers? If yes, then there's a problem with 0-index character of the list.

Comment (Cohee1207) [reply public/scripts/RossAscends-mods.js]: active_character_id was totally broken, cause it's a return value of findIndex which returns -1 if not found, not null.

**Review by Cohee1207 — APPROVED** [review]
Tested. All fields are transferred as needed. Splendid.
