### PR TITLE
Fix `/sendas` to not always enforce avatar, if not needed in solo chats

### LINKED ISSUE #2820: [BUG] `/sendas name=` command forces name prefix even if name matches active solo chat card
### Environment

🪟 Windows

### System

Firefox

### Version

1.12.5 'staging' (1582974b)

### Desktop Information

_No response_

### Describe the problem

`/sendas name=Char message` forces the "Char:" prefix even when you are solo chatting with Char. This occurs with both CC's "Default" or TC's "Force for Groups and Personas" ("Include Names" off). Effectively, a slash commanded message is treated like a doppelganger group chat member taking the same avatar.

Expected: Don't force name prefix for `/sendas` messages when name matches the solo chat card and CC set to Default or TC set to Force for Groups ("Include Names" off).

### Additional info

(User `/send` messages behave correctly.)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) important

### PR DESCRIPTION
**Pull request by Wolfsblvt**
The ages old `/sendas` slash command had a pretty easy logic finding the target character.
But set the avatar url via `force_avatar`. Which would be okay in itself, enforcing that specific image. But the same field gets used in some places to decide whether there was manual modification of the message.

For example Text Completion uses it to decide whether the name prefix is getting added, even if the general name prefix setting is turned off.
Makes sense for Text Completion in case you write a different character into your chat in a solo chat. But if you are in a solo chat, and add a message for that character, there is no need for the name prefix.

Instead of dabbling with Text Completion instruct formatting or deeper stuff like this, we simply can just not set the avatar if character to send as is the same as you are currently chatting with.

- Fixes #2820

## Checklist:

- [x] I have read the [Contributing guidelines](https://www.youtube.com/watch?v=dQw4w9WgXcQ).

### CODE REVIEW

File: public/scripts/slash-commands.js [hunk 1]
```diff
@@ -3129,7 +3129,10 @@ export async function sendMessageAs(args, text) {
     const character = characters.find(x => x.avatar === name) ?? characters.find(x => x.name === name);
     let force_avatar, original_avatar;
 
-    if (character && character.avatar !== 'none') {
+    if (characters[this_chid] === character) {
```
Comment (Cohee1207) [inline public/scripts/slash-commands.js]: I think this would cause fallback avatars not to be set in group chats when used with an unknown character.
`characters[this_chid] === undefined` because we're in a group
`character === undefined` because this is not a known character.

Comment (Cohee1207) [reply public/scripts/slash-commands.js]: As a possible solution - just check that we're not in a group as a part of the condition

Comment (Cohee1207) [reply public/scripts/slash-commands.js]: Also, please check that in the Assistant/no-char chats.

Comment (Wolfsblvt) [reply public/scripts/slash-commands.js]: True, I should check about `this_chid` being truthy too. I thought it was implicitly checked if the entry was not found, but you can also not target an existing character, where you want the default avatar then.

Man, I fucked this up like four times.
Should be correct now.

**Review by Cohee1207 — APPROVED** [review]
Tried all cases. Appears to work fine.
